import type { MealPlan } from '@/types/meal.types'

const PLAN_A: MealPlan = {
  generatedAt: new Date().toISOString(),
  days: [
    {
      day: 'Monday',
      breakfast: {
        name: 'Spinach Paneer Paratha',
        calories: 340,
        protein: 18,
        sugar: 3,
        prepTime: '15 min',
        usesFridgeItems: ['Spinach', 'Paneer', 'Wheat Flour', 'Onions'],
        recipe: {
          ingredients: ['1 cup wheat flour', '100g paneer crumbled', '1 cup spinach blanched and chopped', '¼ onion finely diced', '1 tsp cumin', 'Salt to taste', '2 tbsp oil'],
          steps: ['Mix wheat flour with water to make dough.', 'Mix paneer, spinach, onion, cumin, and salt for filling.', 'Roll dough, add filling, seal and flatten.', 'Cook on a hot griddle with oil until golden on both sides.'],
        },
      },
      lunch: {
        name: 'Tomato Paneer Curry with Rice',
        calories: 480,
        protein: 24,
        sugar: 8,
        prepTime: '25 min',
        usesFridgeItems: ['Tomatoes', 'Paneer', 'Onions'],
        recipe: {
          ingredients: ['200g paneer cubed', '3 tomatoes pureed', '1 onion diced', '2 tbsp oil', '1 tsp garam masala', '½ cup cream or milk', '1 cup cooked rice'],
          steps: ['Sauté onion until golden.', 'Add tomato puree, cook 5 min.', 'Add paneer, garam masala, and milk. Simmer 5 min.', 'Serve over rice.'],
        },
      },
      snack: {
        name: 'Cucumber Tomato Salad with Nuts',
        calories: 150,
        protein: 6,
        sugar: 5,
        prepTime: '5 min',
        usesFridgeItems: ['Cucumber', 'Tomatoes', 'Onions', 'Nuts'],
        recipe: {
          ingredients: ['1 cucumber diced', '2 tomatoes diced', '¼ onion sliced', '2 tbsp chopped nuts', '1 tbsp lemon juice', 'Salt and pepper'],
          steps: ['Combine cucumber, tomatoes, and onion in a bowl.', 'Add nuts, lemon juice, salt, and pepper. Toss and serve.'],
        },
      },
      dinner: {
        name: 'Palak Paneer with Chapati',
        calories: 520,
        protein: 22,
        sugar: 6,
        prepTime: '30 min',
        usesFridgeItems: ['Spinach', 'Paneer', 'Onions', 'Wheat Flour'],
        recipe: {
          ingredients: ['2 cups spinach', '150g paneer', '1 onion', '2 tomatoes', '2 tbsp oil', '1 tsp cumin', 'Wheat flour chapatis'],
          steps: ['Blanch spinach, blend to paste.', 'Sauté onion and tomatoes, add spinach paste.', 'Add paneer cubes, simmer 5 min.', 'Serve with warm chapatis.'],
        },
      },
    },
    {
      day: 'Tuesday',
      breakfast: {
        name: 'Milk Oats with Nuts and Sweet Potato',
        calories: 320,
        protein: 12,
        sugar: 14,
        prepTime: '15 min',
        usesFridgeItems: ['Milk', 'Nuts', 'Sweet potato'],
        recipe: {
          ingredients: ['1 cup milk', '½ cup oats', '½ cup sweet potato cubed and steamed', '2 tbsp chopped nuts', '1 tsp honey'],
          steps: ['Cook oats in milk until creamy.', 'Add steamed sweet potato cubes.', 'Top with nuts and honey.'],
        },
      },
      lunch: {
        name: 'Stuffed Bell Pepper with Paneer',
        calories: 420,
        protein: 20,
        sugar: 6,
        prepTime: '35 min',
        usesFridgeItems: ['Bell pepper', 'Paneer', 'Tomatoes', 'Onions', 'Cheese'],
        recipe: {
          ingredients: ['2 bell peppers halved', '150g paneer crumbled', '1 tomato diced', '½ onion diced', '50g cheese', '1 tsp paprika'],
          steps: ['Scoop out pepper halves.', 'Sauté onion, tomato, paneer. Stuff into peppers.', 'Top with cheese, bake at 375°F for 20 min.'],
        },
      },
      snack: {
        name: 'Cheese and Cucumber Bites',
        calories: 180,
        protein: 10,
        sugar: 2,
        prepTime: '5 min',
        usesFridgeItems: ['Cheese', 'Cucumber'],
        recipe: {
          ingredients: ['50g cheese cubed', '1 cucumber sliced', 'Pinch of black pepper'],
          steps: ['Slice cucumber into rounds.', 'Top each with a small cheese cube.', 'Sprinkle with pepper.'],
        },
      },
      dinner: {
        name: 'Sweet Potato and Spinach Curry',
        calories: 450,
        protein: 9,
        sugar: 12,
        prepTime: '35 min',
        usesFridgeItems: ['Sweet potato', 'Spinach', 'Tomatoes', 'Onions'],
        recipe: {
          ingredients: ['2 sweet potatoes cubed', '2 cups spinach', '2 tomatoes', '1 onion', '2 tbsp oil', '1 tsp turmeric', '1 tsp cumin'],
          steps: ['Sauté onion until soft.', 'Add tomatoes, turmeric, cumin. Cook 3 min.', 'Add sweet potato and 1 cup water. Simmer 15 min.', 'Stir in spinach, cook 2 min.'],
        },
      },
    },
    {
      day: 'Wednesday',
      breakfast: {
        name: 'Tomato Cheese Toast',
        calories: 310,
        protein: 14,
        sugar: 4,
        prepTime: '10 min',
        usesFridgeItems: ['Tomatoes', 'Cheese'],
        recipe: {
          ingredients: ['2 slices whole wheat bread', '2 tomatoes sliced', '50g cheese grated', '1 tbsp olive oil', 'Oregano'],
          steps: ['Toast bread lightly.', 'Layer tomato slices, top with cheese.', 'Broil until cheese melts. Sprinkle oregano.'],
        },
      },
      lunch: {
        name: 'Paneer and Veggie Wrap',
        calories: 460,
        protein: 22,
        sugar: 5,
        prepTime: '15 min',
        usesFridgeItems: ['Paneer', 'Cucumber', 'Bell pepper', 'Tomatoes', 'Onions'],
        recipe: {
          ingredients: ['100g paneer grilled', '1 whole wheat wrap', '½ cucumber sliced', '½ bell pepper sliced', '1 tomato sliced', '¼ onion', '2 tbsp cheese'],
          steps: ['Warm the wrap.', 'Layer paneer, cucumber, pepper, tomato, onion.', 'Add cheese, roll tightly.'],
        },
      },
      snack: {
        name: 'Sweet Potato and Nut Mix',
        calories: 200,
        protein: 6,
        sugar: 8,
        prepTime: '10 min',
        usesFridgeItems: ['Sweet potato', 'Nuts'],
        recipe: {
          ingredients: ['1 small sweet potato baked', '2 tbsp mixed nuts', 'Pinch of cinnamon'],
          steps: ['Bake or microwave sweet potato until soft.', 'Slice and top with nuts and cinnamon.'],
        },
      },
      dinner: {
        name: 'Spinach and Paneer Stuffed Paratha',
        calories: 500,
        protein: 20,
        sugar: 4,
        prepTime: '25 min',
        usesFridgeItems: ['Spinach', 'Paneer', 'Wheat Flour', 'Onions'],
        recipe: {
          ingredients: ['1 cup wheat flour', '100g paneer', '1 cup spinach', '¼ onion', '1 tsp cumin', 'Salt', '2 tbsp oil'],
          steps: ['Make dough from wheat flour.', 'Mix paneer, spinach, onion, cumin for filling.', 'Stuff, roll, and cook parathas on griddle.'],
        },
      },
    },
    {
      day: 'Thursday',
      breakfast: {
        name: 'Milk and Wheat Flour Porridge',
        calories: 280,
        protein: 10,
        sugar: 18,
        prepTime: '12 min',
        usesFridgeItems: ['Milk', 'Wheat Flour', 'Nuts'],
        recipe: {
          ingredients: ['1 cup milk', '3 tbsp wheat flour', '2 tbsp chopped nuts', '1 tbsp jaggery or sugar'],
          steps: ['Mix wheat flour with a little milk to make paste.', 'Boil remaining milk, add paste, stir until thick.', 'Top with nuts and jaggery.'],
        },
      },
      lunch: {
        name: 'Tomato Spinach Pasta',
        calories: 440,
        protein: 18,
        sugar: 9,
        prepTime: '20 min',
        usesFridgeItems: ['Tomatoes', 'Spinach', 'Onions', 'Cheese'],
        recipe: {
          ingredients: ['150g pasta', '2 cups spinach', '2 tomatoes', '¼ onion', '50g cheese', '2 tbsp olive oil', 'Garlic'],
          steps: ['Cook pasta al dente.', 'Sauté onion and garlic, add tomatoes.', 'Wilt spinach, toss with pasta and cheese.'],
        },
      },
      snack: {
        name: 'Cucumber Raita with Nuts',
        calories: 140,
        protein: 8,
        sugar: 5,
        prepTime: '5 min',
        usesFridgeItems: ['Cucumber', 'Milk', 'Nuts'],
        recipe: {
          ingredients: ['1 cucumber grated', '½ cup yogurt (from milk)', '1 tbsp chopped nuts', 'Cumin and salt'],
          steps: ['Mix grated cucumber with yogurt.', 'Add nuts, cumin, and salt. Chill and serve.'],
        },
      },
      dinner: {
        name: 'Paneer Tikka with Bell Pepper',
        calories: 480,
        protein: 24,
        sugar: 5,
        prepTime: '30 min',
        usesFridgeItems: ['Paneer', 'Bell pepper', 'Onions', 'Tomatoes'],
        recipe: {
          ingredients: ['200g paneer', '1 bell pepper', '1 onion', '2 tomatoes', '2 tbsp yogurt', '1 tsp tandoori masala', '1 tbsp oil'],
          steps: ['Marinate paneer and veggies in yogurt and masala.', 'Thread on skewers or place on tray.', 'Bake at 400°F for 15 min until charred.'],
        },
      },
    },
    {
      day: 'Friday',
      breakfast: {
        name: 'Sweet Potato and Spinach Paratha',
        calories: 350,
        protein: 11,
        sugar: 6,
        prepTime: '20 min',
        usesFridgeItems: ['Sweet potato', 'Spinach', 'Wheat Flour'],
        recipe: {
          ingredients: ['1 cup wheat flour', '1 small sweet potato boiled and mashed', '½ cup spinach chopped', '1 tsp cumin', 'Salt', '2 tbsp oil'],
          steps: ['Mix wheat flour with mashed sweet potato and spinach.', 'Knead into dough.', 'Roll and cook parathas on griddle.'],
        },
      },
      lunch: {
        name: 'Cucumber Tomato Paneer Salad',
        calories: 380,
        protein: 18,
        sugar: 7,
        prepTime: '15 min',
        usesFridgeItems: ['Cucumber', 'Tomatoes', 'Paneer', 'Onions', 'Bell pepper'],
        recipe: {
          ingredients: ['1 cucumber', '2 tomatoes', '100g paneer cubed', '¼ onion', '½ bell pepper', '1 tbsp olive oil', 'Lemon juice', 'Salt'],
          steps: ['Dice all vegetables and paneer.', 'Toss with oil, lemon, and salt.', 'Serve chilled.'],
        },
      },
      snack: {
        name: 'Cheese and Nut Stuffed Tomatoes',
        calories: 190,
        protein: 10,
        sugar: 4,
        prepTime: '10 min',
        usesFridgeItems: ['Tomatoes', 'Cheese', 'Nuts'],
        recipe: {
          ingredients: ['2 large tomatoes', '50g cheese', '2 tbsp chopped nuts', 'Herbs'],
          steps: ['Scoop out tomato pulp.', 'Mix cheese and nuts, stuff into tomatoes.', 'Bake at 375°F for 10 min.'],
        },
      },
      dinner: {
        name: 'Palak Paneer with Wheat Roti',
        calories: 510,
        protein: 22,
        sugar: 6,
        prepTime: '30 min',
        usesFridgeItems: ['Spinach', 'Paneer', 'Onions', 'Tomatoes', 'Wheat Flour'],
        recipe: {
          ingredients: ['2 cups spinach', '150g paneer', '1 onion', '2 tomatoes', 'Wheat flour for roti', '2 tbsp oil', 'Spices'],
          steps: ['Make spinach gravy with onion and tomatoes.', 'Add paneer, simmer.', 'Serve with fresh wheat rotis.'],
        },
      },
    },
  ],
  shoppingList: [
    { name: 'Wheat flour', amount: '1 kg', category: 'Grains' },
    { name: 'Rice', amount: '500g', category: 'Grains' },
    { name: 'Pasta', amount: '250g', category: 'Grains' },
    { name: 'Whole wheat bread', amount: '1 loaf', category: 'Grains' },
    { name: 'Whole wheat wraps', amount: '4 pack', category: 'Grains' },
    { name: 'Garlic', amount: '1 head', category: 'Produce' },
    { name: 'Ginger', amount: '1 piece', category: 'Produce' },
    { name: 'Lemon', amount: '2', category: 'Produce' },
    { name: 'Cilantro', amount: '1 bunch', category: 'Produce' },
    { name: 'Olive oil', amount: '1 bottle', category: 'Pantry' },
    { name: 'Garam masala', amount: '1 small pack', category: 'Pantry' },
    { name: 'Cumin seeds', amount: '50g', category: 'Pantry' },
    { name: 'Turmeric', amount: '50g', category: 'Pantry' },
    { name: 'Tandoori masala', amount: '1 pack', category: 'Pantry' },
    { name: 'Salt', amount: '1 pack', category: 'Pantry' },
    { name: 'Black pepper', amount: '1 pack', category: 'Pantry' },
    { name: 'Oats', amount: '250g', category: 'Pantry' },
    { name: 'Jaggery or sugar', amount: '200g', category: 'Pantry' },
    { name: 'Yogurt culture or plain yogurt', amount: '1 tub', category: 'Dairy' },
  ],
}

const PLAN_B: MealPlan = {
  generatedAt: new Date().toISOString(),
  days: [
    { day: 'Monday', breakfast: { name: 'Paneer Bhurji with Roti', calories: 360, protein: 20, sugar: 4, prepTime: '15 min', usesFridgeItems: ['Paneer', 'Onions', 'Tomatoes', 'Wheat Flour'], recipe: { ingredients: ['150g paneer', '1 onion', '2 tomatoes', 'Wheat flour roti', 'Spices'], steps: ['Crumble paneer. Sauté onion and tomatoes.', 'Add paneer, spices. Serve with roti.'] } }, lunch: { name: 'Tomato Cucumber Paneer Salad', calories: 400, protein: 16, sugar: 6, prepTime: '12 min', usesFridgeItems: ['Tomatoes', 'Cucumber', 'Paneer', 'Onions'], recipe: { ingredients: ['2 tomatoes', '1 cucumber', '100g paneer', '¼ onion', 'Lemon juice'], steps: ['Dice all. Toss with lemon and salt.'] } }, snack: { name: 'Cheese and Nut Stuffed Cucumber', calories: 160, protein: 8, sugar: 2, prepTime: '5 min', usesFridgeItems: ['Cucumber', 'Cheese', 'Nuts'], recipe: { ingredients: ['1 cucumber', '2 tbsp cheese', '1 tbsp nuts'], steps: ['Scoop cucumber. Mix cheese and nuts, stuff.'] } }, dinner: { name: 'Shahi Paneer with Chapati', calories: 530, protein: 24, sugar: 7, prepTime: '30 min', usesFridgeItems: ['Paneer', 'Tomatoes', 'Onions', 'Milk', 'Wheat Flour'], recipe: { ingredients: ['200g paneer', '3 tomatoes', '1 onion', '½ cup milk', 'Chapati'], steps: ['Make tomato-onion gravy.', 'Add paneer and milk. Simmer. Serve with chapati.'] } } },
    { day: 'Tuesday', breakfast: { name: 'Sweet Potato Milk Smoothie', calories: 300, protein: 10, sugar: 12, prepTime: '8 min', usesFridgeItems: ['Sweet potato', 'Milk', 'Nuts'], recipe: { ingredients: ['½ cup sweet potato', '1 cup milk', '2 tbsp nuts'], steps: ['Blend cooked sweet potato, milk, nuts.'] } }, lunch: { name: 'Paneer Sandwich with Veggies', calories: 450, protein: 22, sugar: 5, prepTime: '15 min', usesFridgeItems: ['Paneer', 'Tomatoes', 'Cucumber', 'Bell pepper', 'Cheese'], recipe: { ingredients: ['100g paneer', '1 tomato', 'Cucumber', 'Bell pepper', '2 slices bread', 'Cheese'], steps: ['Sauté paneer. Layer veggies and paneer on bread. Toast.'] } }, snack: { name: 'Spinach and Cheese Bites', calories: 170, protein: 12, sugar: 2, prepTime: '10 min', usesFridgeItems: ['Spinach', 'Cheese'], recipe: { ingredients: ['1 cup spinach', '50g cheese'], steps: ['Wilt spinach. Mix with cheese. Form balls, bake 8 min.'] } }, dinner: { name: 'Matar Paneer with Rice', calories: 500, protein: 22, sugar: 6, prepTime: '28 min', usesFridgeItems: ['Paneer', 'Tomatoes', 'Onions'], recipe: { ingredients: ['150g paneer', '1 cup peas', '2 tomatoes', '1 onion', 'Rice'], steps: ['Make tomato gravy. Add peas and paneer. Serve over rice.'] } } },
    { day: 'Wednesday', breakfast: { name: 'Tomato Cheese Toast', calories: 320, protein: 14, sugar: 4, prepTime: '10 min', usesFridgeItems: ['Tomatoes', 'Cheese'], recipe: { ingredients: ['2 tomatoes', '50g cheese', '2 bread slices'], steps: ['Toast bread. Layer tomato and cheese. Broil.'] } }, lunch: { name: 'Bell Pepper Stuffed with Paneer', calories: 430, protein: 20, sugar: 6, prepTime: '35 min', usesFridgeItems: ['Bell pepper', 'Paneer', 'Tomatoes', 'Onions', 'Cheese'], recipe: { ingredients: ['2 peppers', '150g paneer', '1 tomato', '½ onion', 'Cheese'], steps: ['Sauté filling. Stuff peppers. Bake 20 min.'] } }, snack: { name: 'Cucumber with Nut Dip', calories: 140, protein: 5, sugar: 3, prepTime: '5 min', usesFridgeItems: ['Cucumber', 'Nuts'], recipe: { ingredients: ['1 cucumber', '2 tbsp ground nuts'], steps: ['Slice cucumber. Serve with nut dip.'] } }, dinner: { name: 'Paneer Butter Masala with Roti', calories: 520, protein: 24, sugar: 8, prepTime: '30 min', usesFridgeItems: ['Paneer', 'Tomatoes', 'Onions', 'Milk', 'Wheat Flour'], recipe: { ingredients: ['200g paneer', '3 tomatoes', '1 onion', 'Milk', 'Roti'], steps: ['Make tomato-onion gravy. Add paneer, milk, butter. Serve with roti.'] } } },
    { day: 'Thursday', breakfast: { name: 'Wheat Flour Dosa with Tomato Chutney', calories: 340, protein: 8, sugar: 5, prepTime: '20 min', usesFridgeItems: ['Wheat Flour', 'Tomatoes', 'Onions'], recipe: { ingredients: ['1 cup wheat flour', '2 tomatoes', '¼ onion', 'Spices'], steps: ['Make tomato chutney. Make dosa batter. Cook dosas.'] } }, lunch: { name: 'Spinach Paneer Paratha', calories: 470, protein: 20, sugar: 4, prepTime: '20 min', usesFridgeItems: ['Spinach', 'Paneer', 'Wheat Flour', 'Onions'], recipe: { ingredients: ['1 cup wheat flour', '100g paneer', '1 cup spinach', 'Onion'], steps: ['Make filling. Stuff parathas. Cook.'] } }, snack: { name: 'Sweet Potato with Nuts', calories: 200, protein: 6, sugar: 8, prepTime: '12 min', usesFridgeItems: ['Sweet potato', 'Nuts'], recipe: { ingredients: ['1 sweet potato', '2 tbsp nuts'], steps: ['Bake sweet potato. Top with nuts.'] } }, dinner: { name: 'Paneer Tikka with Bell Pepper', calories: 490, protein: 24, sugar: 5, prepTime: '30 min', usesFridgeItems: ['Paneer', 'Bell pepper', 'Onions', 'Tomatoes'], recipe: { ingredients: ['200g paneer', '1 pepper', '1 onion', '2 tomatoes'], steps: ['Marinate. Bake at 400°F for 15 min.'] } } },
    { day: 'Friday', breakfast: { name: 'Milk Oats with Spinach', calories: 290, protein: 12, sugar: 10, prepTime: '12 min', usesFridgeItems: ['Milk', 'Spinach', 'Nuts'], recipe: { ingredients: ['1 cup milk', '½ cup oats', '½ cup spinach', 'Nuts'], steps: ['Cook oats in milk. Add spinach. Top with nuts.'] } }, lunch: { name: 'Paneer Tikka Wrap', calories: 460, protein: 22, sugar: 5, prepTime: '20 min', usesFridgeItems: ['Paneer', 'Bell pepper', 'Onions', 'Cucumber', 'Tomatoes'], recipe: { ingredients: ['100g paneer', 'Pepper', 'Onion', 'Cucumber', 'Tomato', 'Wrap'], steps: ['Grill paneer and veggies. Roll in wrap.'] } }, snack: { name: 'Tomato Cheese Bites', calories: 180, protein: 10, sugar: 3, prepTime: '8 min', usesFridgeItems: ['Tomatoes', 'Cheese'], recipe: { ingredients: ['2 tomatoes', '50g cheese'], steps: ['Halve tomatoes. Top with cheese. Bake 8 min.'] } }, dinner: { name: 'Palak Paneer with Paratha', calories: 510, protein: 22, sugar: 6, prepTime: '30 min', usesFridgeItems: ['Spinach', 'Paneer', 'Wheat Flour', 'Onions'], recipe: { ingredients: ['2 cups spinach', '150g paneer', 'Wheat flour', 'Onion'], steps: ['Make palak gravy. Add paneer. Serve with paratha.'] } } },
  ],
  shoppingList: [
    { name: 'Wheat flour', amount: '1 kg', category: 'Grains' },
    { name: 'Rice', amount: '500g', category: 'Grains' },
    { name: 'Bread', amount: '1 loaf', category: 'Grains' },
    { name: 'Wraps', amount: '4 pack', category: 'Grains' },
    { name: 'Green peas', amount: '200g', category: 'Produce' },
    { name: 'Garlic', amount: '1 head', category: 'Produce' },
    { name: 'Ginger', amount: '1 piece', category: 'Produce' },
    { name: 'Lemon', amount: '2', category: 'Produce' },
    { name: 'Olive oil', amount: '1 bottle', category: 'Pantry' },
    { name: 'Garam masala', amount: '1 pack', category: 'Pantry' },
    { name: 'Butter', amount: '100g', category: 'Dairy' },
    { name: 'Oats', amount: '250g', category: 'Pantry' },
  ],
}

const PLAN_C: MealPlan = {
  generatedAt: new Date().toISOString(),
  days: [
    { day: 'Monday', breakfast: { name: 'Cheese Tomato Omelette-Style Paratha', calories: 350, protein: 16, sugar: 4, prepTime: '15 min', usesFridgeItems: ['Cheese', 'Tomatoes', 'Wheat Flour', 'Onions'], recipe: { ingredients: ['1 cup wheat flour', '50g cheese', '1 tomato', '¼ onion'], steps: ['Make paratha. Mix cheese, tomato, onion. Stuff and cook.'] } }, lunch: { name: 'Cucumber Paneer Raita with Rice', calories: 420, protein: 18, sugar: 6, prepTime: '15 min', usesFridgeItems: ['Cucumber', 'Paneer', 'Milk'], recipe: { ingredients: ['1 cucumber', '100g paneer', 'Yogurt', 'Rice'], steps: ['Make raita with cucumber and paneer. Serve with rice.'] } }, snack: { name: 'Bell Pepper with Nut Butter', calories: 150, protein: 6, sugar: 2, prepTime: '5 min', usesFridgeItems: ['Bell pepper', 'Nuts'], recipe: { ingredients: ['1 bell pepper', '2 tbsp nut butter'], steps: ['Slice pepper. Serve with nut butter.'] } }, dinner: { name: 'Paneer Jalfrezi with Roti', calories: 500, protein: 22, sugar: 7, prepTime: '25 min', usesFridgeItems: ['Paneer', 'Bell pepper', 'Onions', 'Tomatoes', 'Wheat Flour'], recipe: { ingredients: ['150g paneer', '1 pepper', '1 onion', '2 tomatoes', 'Roti'], steps: ['Stir-fry paneer and veggies. Serve with roti.'] } } },
    { day: 'Tuesday', breakfast: { name: 'Sweet Potato Paratha', calories: 330, protein: 8, sugar: 6, prepTime: '20 min', usesFridgeItems: ['Sweet potato', 'Wheat Flour'], recipe: { ingredients: ['1 sweet potato', '1 cup wheat flour'], steps: ['Mash sweet potato. Mix with flour. Cook parathas.'] } }, lunch: { name: 'Tomato Spinach Paneer Curry', calories: 440, protein: 22, sugar: 8, prepTime: '25 min', usesFridgeItems: ['Tomatoes', 'Spinach', 'Paneer', 'Onions'], recipe: { ingredients: ['2 tomatoes', '2 cups spinach', '150g paneer', '1 onion'], steps: ['Make tomato-spinach gravy. Add paneer.'] } }, snack: { name: 'Cheese and Tomato Skewers', calories: 170, protein: 10, sugar: 3, prepTime: '10 min', usesFridgeItems: ['Cheese', 'Tomatoes'], recipe: { ingredients: ['50g cheese', '2 tomatoes'], steps: ['Alternate cheese and tomato. Grill or bake 5 min.'] } }, dinner: { name: 'Kadai Paneer with Naan', calories: 520, protein: 24, sugar: 6, prepTime: '30 min', usesFridgeItems: ['Paneer', 'Bell pepper', 'Onions', 'Tomatoes', 'Wheat Flour'], recipe: { ingredients: ['200g paneer', '1 pepper', '1 onion', '2 tomatoes', 'Wheat flour naan'], steps: ['Make kadai gravy. Add paneer and pepper. Serve with naan.'] } } },
    { day: 'Wednesday', breakfast: { name: 'Milk and Wheat Flour Halwa', calories: 310, protein: 10, sugar: 20, prepTime: '15 min', usesFridgeItems: ['Milk', 'Wheat Flour', 'Nuts'], recipe: { ingredients: ['1 cup milk', '4 tbsp wheat flour', '2 tbsp nuts', 'Ghee'], steps: ['Roast flour in ghee. Add milk, stir until thick. Top with nuts.'] } }, lunch: { name: 'Paneer Tikka Salad Bowl', calories: 430, protein: 22, sugar: 5, prepTime: '25 min', usesFridgeItems: ['Paneer', 'Cucumber', 'Tomatoes', 'Onions', 'Bell pepper'], recipe: { ingredients: ['150g paneer', 'Cucumber', 'Tomatoes', 'Onion', 'Pepper'], steps: ['Bake paneer tikka. Toss with fresh veggies.'] } }, snack: { name: 'Spinach and Cheese Roll', calories: 180, protein: 12, sugar: 2, prepTime: '12 min', usesFridgeItems: ['Spinach', 'Cheese', 'Wheat Flour'], recipe: { ingredients: ['1 cup spinach', '50g cheese', 'Wheat flour'], steps: ['Make thin roti. Wrap spinach and cheese.'] } }, dinner: { name: 'Palak Paneer with Rice', calories: 490, protein: 22, sugar: 6, prepTime: '30 min', usesFridgeItems: ['Spinach', 'Paneer', 'Onions', 'Tomatoes'], recipe: { ingredients: ['2 cups spinach', '150g paneer', '1 onion', '2 tomatoes', 'Rice'], steps: ['Make palak gravy. Add paneer. Serve with rice.'] } } },
    { day: 'Thursday', breakfast: { name: 'Tomato Cheese Toast', calories: 300, protein: 14, sugar: 4, prepTime: '10 min', usesFridgeItems: ['Tomatoes', 'Cheese'], recipe: { ingredients: ['2 tomatoes', '50g cheese', '2 bread slices'], steps: ['Toast. Layer tomato and cheese. Broil.'] } }, lunch: { name: 'Paneer Bhurji Wrap', calories: 450, protein: 22, sugar: 5, prepTime: '15 min', usesFridgeItems: ['Paneer', 'Tomatoes', 'Onions', 'Bell pepper'], recipe: { ingredients: ['150g paneer', '1 tomato', '½ onion', 'Pepper', 'Wrap'], steps: ['Make paneer bhurji. Roll in wrap.'] } }, snack: { name: 'Cucumber Tomato Salsa with Nuts', calories: 140, protein: 5, sugar: 5, prepTime: '5 min', usesFridgeItems: ['Cucumber', 'Tomatoes', 'Onions', 'Nuts'], recipe: { ingredients: ['1 cucumber', '2 tomatoes', 'Onion', 'Nuts'], steps: ['Dice all. Mix. Add nuts.'] } }, dinner: { name: 'Paneer Kofta in Tomato Gravy', calories: 520, protein: 24, sugar: 8, prepTime: '35 min', usesFridgeItems: ['Paneer', 'Tomatoes', 'Onions'], recipe: { ingredients: ['200g paneer', '3 tomatoes', '1 onion', 'Spices'], steps: ['Make paneer balls. Make tomato gravy. Add koftas.'] } } },
    { day: 'Friday', breakfast: { name: 'Spinach Cheese Paratha', calories: 340, protein: 16, sugar: 3, prepTime: '18 min', usesFridgeItems: ['Spinach', 'Cheese', 'Wheat Flour'], recipe: { ingredients: ['1 cup wheat flour', '1 cup spinach', '50g cheese'], steps: ['Mix spinach and cheese. Stuff parathas. Cook.'] } }, lunch: { name: 'Sweet Potato and Paneer Bowl', calories: 420, protein: 18, sugar: 10, prepTime: '25 min', usesFridgeItems: ['Sweet potato', 'Paneer', 'Spinach', 'Onions'], recipe: { ingredients: ['1 sweet potato', '100g paneer', '1 cup spinach', 'Onion'], steps: ['Roast sweet potato. Sauté paneer and spinach. Assemble.'] } }, snack: { name: 'Cheese and Nut Balls', calories: 190, protein: 10, sugar: 2, prepTime: '8 min', usesFridgeItems: ['Cheese', 'Nuts'], recipe: { ingredients: ['50g cheese', '2 tbsp nuts'], steps: ['Mix. Form balls. Chill.'] } }, dinner: { name: 'Paneer Butter Masala with Chapati', calories: 510, protein: 24, sugar: 7, prepTime: '30 min', usesFridgeItems: ['Paneer', 'Tomatoes', 'Onions', 'Milk', 'Wheat Flour'], recipe: { ingredients: ['200g paneer', '3 tomatoes', '1 onion', 'Milk', 'Chapati'], steps: ['Make tomato gravy. Add paneer, milk, butter. Serve with chapati.'] } } },
  ],
  shoppingList: [
    { name: 'Wheat flour', amount: '1 kg', category: 'Grains' },
    { name: 'Rice', amount: '500g', category: 'Grains' },
    { name: 'Bread', amount: '1 loaf', category: 'Grains' },
    { name: 'Wraps', amount: '4 pack', category: 'Grains' },
    { name: 'Garlic', amount: '1 head', category: 'Produce' },
    { name: 'Ginger', amount: '1 piece', category: 'Produce' },
    { name: 'Lemon', amount: '2', category: 'Produce' },
    { name: 'Cilantro', amount: '1 bunch', category: 'Produce' },
    { name: 'Olive oil', amount: '1 bottle', category: 'Pantry' },
    { name: 'Garam masala', amount: '1 pack', category: 'Pantry' },
    { name: 'Ghee', amount: '200g', category: 'Pantry' },
    { name: 'Butter', amount: '100g', category: 'Dairy' },
  ],
}

const PLAN_D: MealPlan = {
  generatedAt: new Date().toISOString(),
  days: [
    {
      day: 'Monday',
      breakfast: {
        name: 'Eggs and Cheese Scramble with Tomatoes',
        calories: 320,
        protein: 22,
        sugar: 4,
        prepTime: '12 min',
        usesFridgeItems: ['Eggs', 'Cheese', 'Tomatoes', 'Onions'],
        recipe: {
          ingredients: ['3 eggs', '50g cheese', '1 tomato diced', '¼ onion', 'Salt and pepper', '1 tbsp oil'],
          steps: ['Whisk eggs. Sauté onion and tomato.', 'Add eggs, scramble. Fold in cheese.'],
        },
      },
      lunch: {
        name: 'Paneer and Veggie Wrap',
        calories: 450,
        protein: 24,
        sugar: 5,
        prepTime: '20 min',
        usesFridgeItems: ['Paneer', 'Cucumber', 'Bell pepper', 'Tomatoes', 'Onions'],
        recipe: {
          ingredients: ['150g paneer grilled', '1 wrap', '½ cucumber', '½ bell pepper', '1 tomato', '¼ onion', 'Lemon juice'],
          steps: ['Slice paneer. Warm wrap.', 'Layer paneer and veggies. Drizzle lemon. Roll.'],
        },
      },
      snack: {
        name: 'Blueberries with Nuts',
        calories: 140,
        protein: 4,
        sugar: 12,
        prepTime: '2 min',
        usesFridgeItems: ['Blueberries', 'Nuts'],
        recipe: {
          ingredients: ['1 cup blueberries', '2 tbsp mixed nuts'],
          steps: ['Rinse blueberries. Serve with nuts.'],
        },
      },
      dinner: {
        name: 'Lemon Paneer with Carrots and Rice',
        calories: 520,
        protein: 24,
        sugar: 8,
        prepTime: '35 min',
        usesFridgeItems: ['Paneer', 'Lemons', 'Carrots', 'Onions'],
        recipe: {
          ingredients: ['200g paneer', '2 lemons juiced', '2 carrots sliced', '1 onion', '1 cup rice', '2 tbsp oil'],
          steps: ['Marinate paneer in lemon. Sauté onion and carrots.', 'Add paneer, cook through. Serve over rice.'],
        },
      },
    },
    {
      day: 'Tuesday',
      breakfast: {
        name: 'Blueberry Oats with Milk',
        calories: 300,
        protein: 12,
        sugar: 16,
        prepTime: '10 min',
        usesFridgeItems: ['Blueberries', 'Milk', 'Nuts'],
        recipe: {
          ingredients: ['1 cup milk', '½ cup oats', '½ cup blueberries', '2 tbsp nuts'],
          steps: ['Cook oats in milk. Top with blueberries and nuts.'],
        },
      },
      lunch: {
        name: 'Carrot and Paneer Salad',
        calories: 380,
        protein: 22,
        sugar: 10,
        prepTime: '15 min',
        usesFridgeItems: ['Carrots', 'Paneer', 'Cucumber', 'Tomatoes', 'Lemons'],
        recipe: {
          ingredients: ['2 carrots grated', '150g paneer crumbled', '½ cucumber', '1 tomato', '1 lemon juiced'],
          steps: ['Combine crumbled paneer and veggies.', 'Toss with lemon juice and salt.'],
        },
      },
      snack: {
        name: 'Cheese and Carrot Sticks',
        calories: 150,
        protein: 8,
        sugar: 4,
        prepTime: '5 min',
        usesFridgeItems: ['Cheese', 'Carrots'],
        recipe: {
          ingredients: ['50g cheese', '2 carrots cut into sticks'],
          steps: ['Cut cheese into cubes. Arrange with carrot sticks.'],
        },
      },
      dinner: {
        name: 'Egg Fried Rice with Veggies',
        calories: 480,
        protein: 20,
        sugar: 6,
        prepTime: '25 min',
        usesFridgeItems: ['Eggs', 'Onions', 'Carrots', 'Tomatoes'],
        recipe: {
          ingredients: ['2 eggs', '2 cups cooked rice', '1 carrot diced', '¼ onion', '1 tomato', '2 tbsp oil'],
          steps: ['Scramble eggs, set aside. Stir-fry veggies.', 'Add rice and eggs. Toss and serve.'],
        },
      },
    },
    {
      day: 'Wednesday',
      breakfast: {
        name: 'Lemon Blueberry Parfait',
        calories: 280,
        protein: 10,
        sugar: 18,
        prepTime: '8 min',
        usesFridgeItems: ['Lemons', 'Blueberries', 'Milk', 'Nuts'],
        recipe: {
          ingredients: ['1 cup yogurt', '1 cup blueberries', '1 lemon zested', '2 tbsp nuts'],
          steps: ['Layer yogurt, blueberries, lemon zest. Top with nuts.'],
        },
      },
      lunch: {
        name: 'Paneer Curry with Rice',
        calories: 520,
        protein: 24,
        sugar: 7,
        prepTime: '30 min',
        usesFridgeItems: ['Paneer', 'Tomatoes', 'Onions', 'Lemons'],
        recipe: {
          ingredients: ['250g paneer cubed', '2 tomatoes', '1 onion', '1 lemon', 'Rice', 'Spices'],
          steps: ['Make tomato-onion gravy. Add paneer, cook 5 min.', 'Add lemon juice. Serve over rice.'],
        },
      },
      snack: {
        name: 'Cucumber Lemon Salad',
        calories: 60,
        protein: 2,
        sugar: 4,
        prepTime: '5 min',
        usesFridgeItems: ['Cucumber', 'Lemons', 'Onions'],
        recipe: {
          ingredients: ['1 cucumber sliced', '1 lemon juiced', '¼ onion', 'Salt'],
          steps: ['Combine cucumber and onion. Dress with lemon and salt.'],
        },
      },
      dinner: {
        name: 'Roasted Paneer with Carrots and Sweet Potato',
        calories: 500,
        protein: 22,
        sugar: 14,
        prepTime: '45 min',
        usesFridgeItems: ['Paneer', 'Carrots', 'Sweet potato', 'Onions'],
        recipe: {
          ingredients: ['200g paneer cubed', '2 carrots', '1 sweet potato', '1 onion', '2 tbsp oil', 'Herbs'],
          steps: ['Season paneer and veggies. Roast at 400°F for 35 min.'],
        },
      },
    },
    {
      day: 'Thursday',
      breakfast: {
        name: 'Eggs with Spinach and Cheese',
        calories: 340,
        protein: 24,
        sugar: 3,
        prepTime: '15 min',
        usesFridgeItems: ['Eggs', 'Spinach', 'Cheese', 'Onions'],
        recipe: {
          ingredients: ['3 eggs', '1 cup spinach', '50g cheese', '¼ onion', '2 tbsp oil'],
          steps: ['Sauté spinach and onion. Add beaten eggs.', 'Scramble, fold in cheese.'],
        },
      },
      lunch: {
        name: 'Lemon Paneer with Bell Pepper',
        calories: 420,
        protein: 22,
        sugar: 6,
        prepTime: '25 min',
        usesFridgeItems: ['Paneer', 'Lemons', 'Bell pepper', 'Onions', 'Tomatoes'],
        recipe: {
          ingredients: ['200g paneer', '2 lemons', '1 bell pepper', '1 onion', '1 tomato', '2 tbsp oil'],
          steps: ['Sauté paneer. Add veggies and lemon juice.', 'Simmer 10 min.'],
        },
      },
      snack: {
        name: 'Blueberry Cheese Bites',
        calories: 160,
        protein: 8,
        sugar: 10,
        prepTime: '5 min',
        usesFridgeItems: ['Blueberries', 'Cheese'],
        recipe: {
          ingredients: ['1 cup blueberries', '50g cheese cubed'],
          steps: ['Alternate blueberries and cheese on skewers or in bowl.'],
        },
      },
      dinner: {
        name: 'Carrot Paneer Curry with Chapati',
        calories: 460,
        protein: 22,
        sugar: 10,
        prepTime: '30 min',
        usesFridgeItems: ['Carrots', 'Paneer', 'Tomatoes', 'Onions', 'Wheat Flour'],
        recipe: {
          ingredients: ['2 carrots', '150g paneer', '2 tomatoes', '1 onion', 'Chapati', 'Spices'],
          steps: ['Make carrot-tomato gravy. Add paneer. Serve with chapati.'],
        },
      },
    },
    {
      day: 'Friday',
      breakfast: {
        name: 'Sweet Carrot Oats with Nuts',
        calories: 310,
        protein: 10,
        sugar: 14,
        prepTime: '12 min',
        usesFridgeItems: ['Carrots', 'Milk', 'Nuts'],
        recipe: {
          ingredients: ['1 carrot grated', '1 cup milk', '½ cup oats', '2 tbsp nuts'],
          steps: ['Cook oats in milk. Add grated carrot. Top with nuts.'],
        },
      },
      lunch: {
        name: 'Egg Salad with Cucumber and Tomatoes',
        calories: 350,
        protein: 20,
        sugar: 6,
        prepTime: '12 min',
        usesFridgeItems: ['Eggs', 'Cucumber', 'Tomatoes', 'Onions', 'Lemons'],
        recipe: {
          ingredients: ['3 eggs hard-boiled', '1 cucumber', '2 tomatoes', '¼ onion', '1 lemon'],
          steps: ['Chop eggs and veggies. Toss with lemon and salt.'],
        },
      },
      snack: {
        name: 'Blueberry Lemon Smoothie',
        calories: 180,
        protein: 6,
        sugar: 22,
        prepTime: '5 min',
        usesFridgeItems: ['Blueberries', 'Lemons', 'Milk'],
        recipe: {
          ingredients: ['1 cup blueberries', '1 lemon juiced', '1 cup milk'],
          steps: ['Blend blueberries, lemon juice, and milk. Serve chilled.'],
        },
      },
      dinner: {
        name: 'Paneer Tikka with Lemon Rice',
        calories: 530,
        protein: 24,
        sugar: 8,
        prepTime: '35 min',
        usesFridgeItems: ['Paneer', 'Lemons', 'Onions', 'Tomatoes'],
        recipe: {
          ingredients: ['200g paneer', '2 lemons', '1 onion', '2 tomatoes', '1 cup rice', 'Yogurt', 'Spices'],
          steps: ['Marinate paneer in yogurt and spices. Grill or bake.', 'Cook rice with lemon zest. Serve together.'],
        },
      },
    },
  ],
  shoppingList: [
    { name: 'Rice', amount: '500g', category: 'Grains' },
    { name: 'Oats', amount: '250g', category: 'Pantry' },
    { name: 'Garlic', amount: '1 head', category: 'Produce' },
    { name: 'Ginger', amount: '1 piece', category: 'Produce' },
    { name: 'Olive oil', amount: '1 bottle', category: 'Pantry' },
    { name: 'Yogurt', amount: '1 tub', category: 'Dairy' },
    { name: 'Tandoori masala', amount: '1 pack', category: 'Pantry' },
    { name: 'Cumin', amount: '50g', category: 'Pantry' },
    { name: 'Salt', amount: '1 pack', category: 'Pantry' },
    { name: 'Black pepper', amount: '1 pack', category: 'Pantry' },
  ],
}

const PLAN_E: MealPlan = {
  generatedAt: new Date().toISOString(),
  days: [
    {
      day: 'Monday',
      breakfast: {
        name: 'Spinach & Paneer Scramble',
        calories: 380,
        protein: 22,
        sugar: 4,
        prepTime: '12 min',
        usesFridgeItems: ['Paneer', 'Spinach', 'Onions', 'Bell pepper'],
        recipe: {
          ingredients: ['150g paneer, crumbled', '1 cup fresh spinach', '½ onion, diced', '½ bell pepper, diced', '1 tsp cumin', '1 tbsp olive oil', 'Salt and pepper to taste'],
          steps: ['Heat olive oil in a pan over medium heat.', 'Sauté onion and bell pepper for 3–4 minutes until softened.', 'Add crumbled paneer and cook 2 minutes until lightly golden.', 'Fold in spinach and cook until wilted, about 1 minute.', 'Season with cumin, salt, and pepper. Serve hot.'],
        },
      },
      lunch: {
        name: 'High-Protein Greek Salad Bowl',
        calories: 520,
        protein: 18,
        sugar: 8,
        prepTime: '15 min',
        usesFridgeItems: ['Cheese', 'Tomatoes', 'Cucumber', 'Spinach'],
        recipe: {
          ingredients: ['2 cups spinach', '1 cup cherry tomatoes, halved', '1 cucumber, diced', '80g feta-style cheese, crumbled', '¼ cup chickpeas, rinsed', '2 tbsp olive oil', '1 lemon, juiced', '1 tsp dried oregano'],
          steps: ['Combine spinach, tomatoes, and cucumber in a large bowl.', 'Add chickpeas and crumbled cheese.', 'Whisk together olive oil, lemon juice, and oregano.', 'Drizzle dressing over salad and toss gently.', 'Serve immediately or refrigerate up to 2 hours.'],
        },
      },
      snack: {
        name: 'Avocado & Carrot Sticks with Hummus',
        calories: 210,
        protein: 4,
        sugar: 6,
        prepTime: '5 min',
        usesFridgeItems: ['Avocado', 'Carrots'],
        recipe: {
          ingredients: ['1 avocado, sliced', '2 large carrots, cut into sticks', '3 tbsp store-bought hummus', 'Pinch of chili flakes'],
          steps: ['Slice avocado and arrange alongside carrot sticks.', 'Serve with hummus for dipping.', 'Sprinkle chili flakes on avocado if desired.'],
        },
      },
      dinner: {
        name: 'Stuffed Bell Peppers with Paneer & Rice',
        calories: 610,
        protein: 24,
        sugar: 8,
        prepTime: '40 min',
        usesFridgeItems: ['Bell pepper', 'Paneer', 'Rice', 'Tomatoes', 'Onions'],
        recipe: {
          ingredients: ['2 large bell peppers, halved and deseeded', '1 cup cooked rice', '150g paneer, cubed', '2 tomatoes, diced', '½ onion, diced', '1 tsp garam masala', '1 tsp cumin', '2 tbsp olive oil', 'Fresh coriander to garnish'],
          steps: ['Preheat oven to 200°C (390°F).', 'Sauté onion in olive oil 3 minutes. Add paneer and cook until golden.', 'Add tomatoes, rice, garam masala, and cumin. Stir and cook 2 minutes.', 'Fill each bell pepper half with the mixture.', 'Place on a baking tray and bake 25 minutes until peppers are tender.', 'Garnish with fresh coriander and serve.'],
        },
      },
    },
    {
      day: 'Tuesday',
      breakfast: {
        name: 'Blueberry Protein Smoothie Bowl',
        calories: 350,
        protein: 20,
        sugar: 18,
        prepTime: '8 min',
        usesFridgeItems: ['Blueberries', 'Milk'],
        recipe: {
          ingredients: ['1 cup blueberries (fresh or frozen)', '¾ cup milk', '1 scoop vanilla protein powder', '1 tbsp almond butter', 'Toppings: granola, extra blueberries, sliced banana'],
          steps: ['Blend blueberries, milk, protein powder, and almond butter until thick and smooth.', 'Pour into a bowl — it should be thicker than a regular smoothie.', 'Add toppings and serve immediately.'],
        },
      },
      lunch: {
        name: 'Sweet Potato & Spinach Curry',
        calories: 490,
        protein: 10,
        sugar: 12,
        prepTime: '30 min',
        usesFridgeItems: ['Sweet potato', 'Spinach', 'Tomatoes', 'Onions'],
        recipe: {
          ingredients: ['1 large sweet potato, cubed', '2 cups spinach', '2 tomatoes, diced', '1 onion, diced', '1 can coconut milk', '2 cloves garlic, minced', '1 tsp turmeric', '1 tsp cumin', '1 tsp coriander', '1 tbsp coconut oil'],
          steps: ['Heat coconut oil and sauté onion and garlic 3 minutes.', 'Add spices and stir 30 seconds until fragrant.', 'Add sweet potato and tomatoes, stir to coat.', 'Pour in coconut milk and simmer 20 minutes until potato is tender.', 'Fold in spinach and cook 2 more minutes. Serve with rice.'],
        },
      },
      snack: {
        name: 'Cheese & Carrot Sticks',
        calories: 180,
        protein: 10,
        sugar: 4,
        prepTime: '3 min',
        usesFridgeItems: ['Cheese', 'Carrots'],
        recipe: {
          ingredients: ['60g cheese, sliced or cubed', '2 large carrots, cut into sticks'],
          steps: ['Slice cheese into portions.', 'Arrange with carrot sticks on a plate.', 'Serve immediately.'],
        },
      },
      dinner: {
        name: 'Paneer Tikka with Wheat Roti',
        calories: 640,
        protein: 32,
        sugar: 6,
        prepTime: '35 min',
        usesFridgeItems: ['Paneer', 'Bell pepper', 'Onions', 'Wheat Flour'],
        recipe: {
          ingredients: ['250g paneer, cubed', '1 bell pepper, cubed', '1 onion, cubed', '½ cup yogurt', '1 tsp chili powder', '1 tsp garam masala', '1 tsp turmeric', '1 tbsp ginger-garlic paste', '1 cup wheat flour (for rotis)', 'Water and salt for dough'],
          steps: ['Mix yogurt with spices and ginger-garlic paste. Add paneer, pepper, and onion. Marinate 20 minutes.', 'Thread onto skewers and grill or pan-fry 10 minutes, turning until charred.', 'For rotis: mix wheat flour, salt, and water into a soft dough. Rest 10 minutes.', 'Divide into balls, roll thin, and cook on a hot dry pan 1 minute per side.', 'Serve tikka with rotis and sliced onion.'],
        },
      },
    },
    {
      day: 'Wednesday',
      breakfast: {
        name: 'Avocado Toast on Wheat Roti',
        calories: 340,
        protein: 8,
        sugar: 4,
        prepTime: '10 min',
        usesFridgeItems: ['Avocado', 'Wheat Flour', 'Lemons', 'Tomatoes'],
        recipe: {
          ingredients: ['1 avocado, mashed', '2 wheat rotis or flatbreads', '½ lemon, juiced', '1 tomato, sliced', 'Chili flakes, salt, pepper'],
          steps: ['Warm rotis in a dry pan.', 'Mash avocado with lemon juice, salt, and pepper.', 'Spread generously on rotis.', 'Top with tomato slices and chili flakes.'],
        },
      },
      lunch: {
        name: 'Cucumber Paneer Protein Bowl',
        calories: 510,
        protein: 24,
        sugar: 5,
        prepTime: '10 min',
        usesFridgeItems: ['Paneer', 'Cucumber', 'Spinach', 'Lemons'],
        recipe: {
          ingredients: ['150g paneer, grilled and sliced', '1 cucumber, diced', '2 cups spinach', '½ lemon, juiced', '1 tbsp olive oil', '1 tsp za\'atar or mixed herbs', 'Salt and pepper'],
          steps: ['Grill paneer slices in a pan with a little oil until golden on each side.', 'Arrange spinach and cucumber in a bowl.', 'Top with warm paneer slices.', 'Drizzle with olive oil and lemon juice, sprinkle za\'atar.'],
        },
      },
      snack: {
        name: 'Blueberry & Cheese Snack Box',
        calories: 190,
        protein: 8,
        sugar: 10,
        prepTime: '2 min',
        usesFridgeItems: ['Blueberries', 'Cheese'],
        recipe: {
          ingredients: ['½ cup blueberries', '50g cheese, sliced'],
          steps: ['Portion into a small box or plate.', 'Serve as is — no prep needed.'],
        },
      },
      dinner: {
        name: 'Sweet Potato & Chickpea Bake',
        calories: 580,
        protein: 16,
        sugar: 14,
        prepTime: '45 min',
        usesFridgeItems: ['Sweet potato', 'Tomatoes', 'Spinach', 'Onions'],
        recipe: {
          ingredients: ['1 large sweet potato, cubed', '1 can chickpeas, drained', '2 tomatoes, quartered', '1 onion, sliced', '2 cups spinach', '3 tbsp olive oil', '1 tsp smoked paprika', '1 tsp cumin', 'Salt and pepper'],
          steps: ['Preheat oven to 200°C. Toss sweet potato, chickpeas, tomatoes, and onion in olive oil and spices.', 'Spread on a baking tray and roast 35 minutes, turning halfway.', 'In last 3 minutes, scatter spinach over the tray and let it wilt.', 'Serve with a squeeze of lemon.'],
        },
      },
    },
    {
      day: 'Thursday',
      breakfast: {
        name: 'Carrot & Nut Overnight Oats',
        calories: 390,
        protein: 12,
        sugar: 16,
        prepTime: '5 min + overnight',
        usesFridgeItems: ['Carrots', 'Nuts', 'Milk', 'Blueberries'],
        recipe: {
          ingredients: ['½ cup rolled oats', '¾ cup milk', '1 carrot, grated', '2 tbsp mixed nuts, chopped', '1 tbsp honey', '½ tsp cinnamon', '¼ cup blueberries to top'],
          steps: ['Combine oats, milk, grated carrot, honey, and cinnamon in a jar.', 'Stir well, cover, and refrigerate overnight.', 'In the morning, top with chopped nuts and blueberries.', 'Eat cold or microwave 90 seconds.'],
        },
      },
      lunch: {
        name: 'Cheese & Veggie Wheat Quesadilla',
        calories: 530,
        protein: 22,
        sugar: 6,
        prepTime: '20 min',
        usesFridgeItems: ['Wheat Flour', 'Cheese', 'Bell pepper', 'Spinach', 'Onions'],
        recipe: {
          ingredients: ['2 wheat tortillas or rolled-out wheat flour dough', '80g cheese, grated', '½ bell pepper, thinly sliced', '½ cup spinach', '¼ onion, thinly sliced', '1 tsp olive oil'],
          steps: ['If using dough, roll into thin circles and cook 1 min per side.', 'Sauté pepper, spinach, and onion in olive oil 3 minutes.', 'Lay one tortilla flat, scatter cheese and veg on half.', 'Fold over and press. Cook in dry pan 2 minutes per side until golden.', 'Slice and serve with yogurt or salsa.'],
        },
      },
      snack: {
        name: 'Avocado with Lemon & Nuts',
        calories: 220,
        protein: 4,
        sugar: 4,
        prepTime: '3 min',
        usesFridgeItems: ['Avocado', 'Lemons', 'Nuts'],
        recipe: {
          ingredients: ['1 avocado, halved', '½ lemon, juiced', '2 tbsp mixed nuts', 'Pinch of sea salt'],
          steps: ['Halve avocado and remove stone.', 'Squeeze lemon juice over each half.', 'Top with nuts and a pinch of sea salt.', 'Eat straight from the skin.'],
        },
      },
      dinner: {
        name: 'Tomato Paneer Rice Bowl',
        calories: 620,
        protein: 26,
        sugar: 10,
        prepTime: '25 min',
        usesFridgeItems: ['Paneer', 'Tomatoes', 'Rice', 'Onions', 'Spinach'],
        recipe: {
          ingredients: ['200g paneer, cubed', '3 tomatoes, blended', '1 cup cooked rice', '1 onion, diced', '2 cups spinach', '2 cloves garlic', '1 tsp cumin seeds', '1 tsp garam masala', '2 tbsp oil'],
          steps: ['Heat oil, add cumin seeds. Once they splutter, add onion and garlic.', 'Sauté 4 minutes, then add blended tomatoes.', 'Cook sauce down 8 minutes until thick and oil separates.', 'Add paneer and garam masala, simmer 5 minutes.', 'Fold in spinach, cook 2 minutes.', 'Serve over rice.'],
        },
      },
    },
    {
      day: 'Friday',
      breakfast: {
        name: 'Mango Lassi Smoothie with Nuts',
        calories: 360,
        protein: 10,
        sugar: 24,
        prepTime: '5 min',
        usesFridgeItems: ['Milk', 'Nuts'],
        recipe: {
          ingredients: ['1 cup yogurt', '½ cup milk', '1 ripe mango (or 1 cup frozen mango)', '1 tbsp honey', '¼ tsp cardamom', '2 tbsp mixed nuts, crushed'],
          steps: ['Blend yogurt, milk, mango, honey, and cardamom until smooth.', 'Pour into a glass.', 'Top with crushed nuts.', 'Serve immediately.'],
        },
      },
      lunch: {
        name: 'Roasted Veggie & Paneer Wrap',
        calories: 540,
        protein: 24,
        sugar: 6,
        prepTime: '30 min',
        usesFridgeItems: ['Paneer', 'Bell pepper', 'Onions', 'Spinach', 'Wheat Flour'],
        recipe: {
          ingredients: ['150g paneer, sliced', '1 bell pepper, sliced', '1 onion, sliced', '1 cup spinach', '2 wheat tortillas', '2 tbsp olive oil', '1 tsp mixed herbs', '2 tbsp hummus or yogurt sauce'],
          steps: ['Toss paneer, pepper, and onion in olive oil and herbs. Roast at 200°C for 20 minutes.', 'Warm tortillas in a dry pan.', 'Spread hummus on each tortilla.', 'Add spinach, then roasted veg and paneer.', 'Roll tightly and serve.'],
        },
      },
      snack: {
        name: 'Carrot Sticks with Avocado Dip',
        calories: 195,
        protein: 3,
        sugar: 6,
        prepTime: '5 min',
        usesFridgeItems: ['Carrots', 'Avocado', 'Lemons'],
        recipe: {
          ingredients: ['2 carrots, cut into sticks', '1 avocado, mashed', '½ lemon, juiced', 'Salt, pepper, chili flakes'],
          steps: ['Mash avocado with lemon juice, salt, and pepper.', 'Arrange carrot sticks on a plate.', 'Serve with avocado dip on the side.'],
        },
      },
      dinner: {
        name: 'Cucumber Raita with Spinach Dal & Rice',
        calories: 590,
        protein: 22,
        sugar: 8,
        prepTime: '35 min',
        usesFridgeItems: ['Spinach', 'Tomatoes', 'Onions', 'Rice', 'Cucumber'],
        recipe: {
          ingredients: ['1 cup red lentils', '2 cups spinach', '2 tomatoes, diced', '1 onion, diced', '1 cup cooked rice', '1 cucumber, grated (for raita)', '½ cup yogurt', '1 tsp cumin seeds', '1 tsp turmeric', '2 tbsp oil', 'Fresh coriander'],
          steps: ['Boil lentils with turmeric in 3 cups water until soft, about 20 minutes.', 'In a pan, heat oil, add cumin seeds, then onion. Sauté 4 minutes.', 'Add tomatoes and cook down 5 minutes. Add spinach and stir.', 'Combine with cooked lentils and simmer 5 more minutes.', 'For raita: mix grated cucumber into yogurt with salt and cumin.', 'Serve dal over rice with raita on the side.'],
        },
      },
    },
  ],
  shoppingList: [
    { name: 'Chickpeas (canned)', amount: '2 cans', category: 'Pantry' },
    { name: 'Coconut milk (canned)', amount: '1 can', category: 'Pantry' },
    { name: 'Red lentils', amount: '1 cup', category: 'Pantry' },
    { name: 'Rolled oats', amount: '½ cup', category: 'Pantry' },
    { name: 'Olive oil', amount: '1 bottle', category: 'Pantry' },
    { name: 'Cumin seeds', amount: '1 jar', category: 'Pantry' },
    { name: 'Garam masala', amount: '1 jar', category: 'Pantry' },
    { name: 'Turmeric', amount: '1 jar', category: 'Pantry' },
    { name: 'Smoked paprika', amount: '1 jar', category: 'Pantry' },
    { name: 'Granola', amount: '200g', category: 'Pantry' },
    { name: 'Honey', amount: '1 jar', category: 'Pantry' },
    { name: 'Hummus', amount: '1 tub', category: 'Pantry' },
    { name: 'Mango (frozen)', amount: '1 cup', category: 'Produce' },
    { name: 'Fresh coriander', amount: '1 bunch', category: 'Produce' },
    { name: 'Garlic', amount: '1 head', category: 'Produce' },
    { name: 'Ginger', amount: '1 knob', category: 'Produce' },
    { name: 'Banana', amount: '×2', category: 'Produce' },
    { name: 'Greek yogurt', amount: '500g', category: 'Dairy' },
    { name: 'Vanilla protein powder', amount: '1 scoop', category: 'Dairy' },
    { name: 'Almond butter', amount: '1 jar', category: 'Pantry' },
    { name: 'Skewers (wooden)', amount: '1 pack', category: 'Pantry' },
  ],
}

export const MOCK_MEAL_PLANS: MealPlan[] = [PLAN_A, PLAN_B, PLAN_C, PLAN_D, PLAN_E]

export function getRandomMockPlan(): MealPlan {
  const plan = MOCK_MEAL_PLANS[Math.floor(Math.random() * MOCK_MEAL_PLANS.length)]
  return { ...plan, generatedAt: new Date().toISOString() }
}
